name: Docker Image CI

on:
  push:
    branches: [ master ]
 

jobs:

  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Client Docker image
      run: docker build -t adityahegde01/hello-world-client ./client
    - name: Build the Server Docker image
      run: docker build -t adityahegde01/hello-world-server ./server
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Push the Client Docker image
      run: docker push adityahegde01/hello-world-client
    - name: Push the Server Docker image
      run: docker push adityahegde01/hello-world-server
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name:  Set pg password apply
      run: |
        kubectl create secret generic pgpassword --from-literal PGPASSWORD=mypassword
    - name:  Kubernetes apply
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx
        kubectl delete -f k8s
        kubectl apply -f k8s

       
      
      
    
