name: Docker Image CI

on:
  push:
    branches: [ master ]
 

jobs:

  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Client Docker image
      run: docker build -t adityahegde01/hello-world-client ./client
    - name: Build the Server Docker image
      run: docker build -t adityahegde01/hello-world-server ./server
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Push the Client Docker image
      run: docker push adityahegde01/hello-world-client
    - name: Push the Server Docker image
      run: docker push adityahegde01/hello-world-server

       
      
      
    
